version: "3.3"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: musedale
      MYSQL_USER: musedale_admin
      MYSQL_PASSWORD: musedale_admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    networks:
      - default
  redis:
    image: "bitnami/redis:5.0"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=lawn_admin
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./redis_data:/bitnami/redis/data"
  bundle:
    build: ./app
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
    command: bash -c "npm install && npm run build"
  migrate:
    build: ./app
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
    command: bash -c "npm run migrate"
  undo_last:
    build: ./app
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
    command: bash -c "npm run undo_last"
  rollback:
    build: ./app
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
    command: bash -c "npm run rollback"
  seed:
    build: ./app
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
    command: bash -c "npm run seed"
  app:
    env_file:
      - "./.env"
    depends_on:
      - db
    build: ./app
    ports:
      - "${PORT}:${PORT}"
      - "${TLS_PORT}:${TLS_PORT}"
    tty: true
    command: bash -c "npm run start"
    networks:
      - default
    volumes:
      - ".env:/usr/src/.env"
      - "./app:/usr/src/app"
      - "./app/node_modules:/usr/src/app/node_modules"
networks:
  default:
